# ==============================================================================
# Phase-shift BRAM timing constraints
# ==============================================================================
# Current clocking in src/bd/design_1_phase_edit.tcl:
#   clk_cpu  : 20 MHz,   0 deg, period 50.000 ns
#   clk_imem : 20 MHz,  90 deg, phase offset +12.500 ns
#   clk_dmem : 20 MHz, 270 deg, phase offset +37.500 ns
#
# These clocks are generated by the same clk_wiz/MMCM. Keep them related so
# Vivado analyzes setup timing between the CPU and both BRAM ports using the
# generated clock phase relationships.
#
# Do not add set_clock_groups -asynchronous or broad set_false_path constraints
# between these clocks.
#
# Why the hold exceptions are needed:
#   With phase-shifted same-frequency clocks, Vivado can perform hold checks
#   against the phase-shifted capture edge in a way that requires tens of ns of
#   minimum delay. That is not the functional intent here. These crossings are
#   intentional same-instruction-cycle transfers; the destination BRAM/CPU edge is
#   used as the setup capture edge, while the old value only needs to be held
#   around the launch edge relationship. The -hold 0 exceptions move the hold
#   check back to that intended edge.
#
# Important functional timing windows:
#   CPU 0 deg -> IMEM 90 deg:
#     PC/address/control must reach IMEM before the +12.5 ns IMEM edge.
#
#   IMEM 90 deg -> DMEM 270 deg:
#     IMEM dout -> decode/regfile/ALU -> DMEM addr/write_data/we must settle
#     before the +37.5 ns DMEM edge. Nominal window is about 25 ns.
#
#   CPU 0 deg -> DMEM 270 deg:
#     Store-related data/control launched from CPU state must also be valid before
#     the +37.5 ns DMEM edge. Nominal window is about 37.5 ns.
#
#   DMEM 270 deg -> CPU 0 deg:
#     DMEM dout -> load align/sign extend -> regfile writeback must settle before
#     the next CPU edge at +50 ns. Nominal window is about 12.5 ns.
# ==============================================================================


# ------------------------------------------------------------------------------
# CPU 0 deg -> IMEM 90 deg
# ------------------------------------------------------------------------------
set_multicycle_path -setup -from [get_clocks clk_cpu_design_1_clk_wiz_0_0] -to [get_clocks clk_imem_design_1_clk_wiz_0_0] 1
set_multicycle_path -hold  -from [get_clocks clk_cpu_design_1_clk_wiz_0_0] -to [get_clocks clk_imem_design_1_clk_wiz_0_0] 0


# ------------------------------------------------------------------------------
# IMEM 90 deg -> CPU 0 deg
# ------------------------------------------------------------------------------
set_multicycle_path -setup -from [get_clocks clk_imem_design_1_clk_wiz_0_0] -to [get_clocks clk_cpu_design_1_clk_wiz_0_0] 1
set_multicycle_path -hold  -from [get_clocks clk_imem_design_1_clk_wiz_0_0] -to [get_clocks clk_cpu_design_1_clk_wiz_0_0] 0


# ------------------------------------------------------------------------------
# CPU 0 deg -> DMEM 270 deg
# ------------------------------------------------------------------------------
set_multicycle_path -setup -from [get_clocks clk_cpu_design_1_clk_wiz_0_0] -to [get_clocks clk_dmem_design_1_clk_wiz_0_0] 1
set_multicycle_path -hold  -from [get_clocks clk_cpu_design_1_clk_wiz_0_0] -to [get_clocks clk_dmem_design_1_clk_wiz_0_0] 0


# ------------------------------------------------------------------------------
# DMEM 270 deg -> CPU 0 deg
# ------------------------------------------------------------------------------
set_multicycle_path -setup -from [get_clocks clk_dmem_design_1_clk_wiz_0_0] -to [get_clocks clk_cpu_design_1_clk_wiz_0_0] 1
set_multicycle_path -hold  -from [get_clocks clk_dmem_design_1_clk_wiz_0_0] -to [get_clocks clk_cpu_design_1_clk_wiz_0_0] 0


# ------------------------------------------------------------------------------
# IMEM 90 deg -> DMEM 270 deg
# ------------------------------------------------------------------------------
set_multicycle_path -setup -from [get_clocks clk_imem_design_1_clk_wiz_0_0] -to [get_clocks clk_dmem_design_1_clk_wiz_0_0] 1
set_multicycle_path -hold  -from [get_clocks clk_imem_design_1_clk_wiz_0_0] -to [get_clocks clk_dmem_design_1_clk_wiz_0_0] 0
