#!/usr/bin/env python3
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BUILD_DIR = SCRIPT_DIR.parent / "software" / "lfc" / "build"


def parse_verilog_words(path: Path) -> list[int]:
    address = 0
    memory: dict[int, int] = {}
    for token in path.read_text(encoding="ascii").split():
        if token.startswith("@"):
            address = int(token[1:], 16)
        else:
            if address in memory:
                raise ValueError(f"duplicate address {address:#x} in {path}")
            memory[address] = int(token, 16)
            address += 1
    if not memory:
        raise ValueError(f"empty image: {path}")
    return [memory.get(index, 0) for index in range(max(memory) + 1)]


def write_header(path: Path, guard: str, symbol: str, words: list[int]) -> None:
    lines = [
        "/* Generated by generate_lfc_vitis_images.py; do not edit manually. */",
        f"#ifndef {guard}", f"#define {guard}", "", "#include <stdint.h>", "",
        f"#define {guard}_WORDS {len(words)}U",
        f"static const uint32_t {symbol}[{guard}_WORDS] = {{",
    ]
    for index in range(0, len(words), 4):
        chunk = words[index:index + 4]
        lines.append("    " + ", ".join(f"0x{word:08X}U" for word in chunk) + ",")
    lines.extend(["};", "", f"#endif /* {guard} */", ""])
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> None:
    baseline_imem = parse_verilog_words(BUILD_DIR / "baseline" / "imem.hex")
    xpc32_imem = parse_verilog_words(BUILD_DIR / "xpc32" / "imem.hex")
    baseline_dmem = parse_verilog_words(BUILD_DIR / "baseline" / "dmem.hex")
    xpc32_dmem = parse_verilog_words(BUILD_DIR / "xpc32" / "dmem.hex")
    if baseline_dmem != xpc32_dmem:
        raise ValueError("baseline and XPC32 DMEM images differ")
    write_header(SCRIPT_DIR / "lfc_imem_baseline.h", "LFC_IMEM_BASELINE", "lfc_imem_baseline", baseline_imem)
    write_header(SCRIPT_DIR / "lfc_imem_xpc32.h", "LFC_IMEM_XPC32", "lfc_imem_xpc32", xpc32_imem)
    write_header(SCRIPT_DIR / "lfc_dmem_image.h", "LFC_DMEM_IMAGE", "lfc_dmem_image", baseline_dmem)
    print(f"baseline IMEM: {len(baseline_imem)} words")
    print(f"XPC32 IMEM:    {len(xpc32_imem)} words")
    print(f"common DMEM:   {len(baseline_dmem)} words")


if __name__ == "__main__":
    main()
