#!/usr/bin/env python3
"""Generate the self-contained image header used by the A53 PS loader."""

from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
LFC_DIR = PROJECT_DIR / "software" / "lfc"
BUILD_DIR = LFC_DIR / "build" / "bdot128"
GENERATED_DIR = LFC_DIR / "generated"
OUTPUT = SCRIPT_DIR / "wide_bdot_images.h"

IMEM_WORDS = 128 * 1024 // 4
DMEM_WORDS = 64 * 1024 // 4
ACT_WORDS = 32 * 1024 // 4
WEIGHT_WORDS = 400 * 1024 // 4
WEIGHT_USED_WORDS = 378112 // 4
INPUT_WORDS = 25


def parse_verilog_words(path: Path) -> dict[int, int]:
    address = 0
    memory: dict[int, int] = {}
    for token in path.read_text(encoding="ascii").split():
        if token.startswith("@"):  # objcopy address is a 32-bit word address
            address = int(token[1:], 16)
        else:
            if address in memory:
                raise ValueError(f"duplicate word address {address:#x} in {path}")
            memory[address] = int(token, 16)
            address += 1
    if not memory:
        raise ValueError(f"empty image: {path}")
    return memory


def parse_plain_hex(path: Path) -> list[int]:
    return [int(line, 16) for line in path.read_text(encoding="ascii").splitlines()]


def contiguous_image(memory: dict[int, int], capacity: int, name: str) -> tuple[int, list[int]]:
    first = min(memory)
    last = max(memory)
    if last >= capacity:
        raise ValueError(f"{name} last word {last:#x} exceeds capacity {capacity:#x}")
    return first, [memory.get(index, 0) for index in range(first, last + 1)]


def render_array(symbol: str, values: list[int]) -> list[str]:
    lines = [f"static const uint32_t {symbol}[{len(values)}U] = {{"]
    for index in range(0, len(values), 4):
        chunk = values[index:index + 4]
        lines.append("    " + ", ".join(f"0x{word:08X}U" for word in chunk) + ",")
    lines.append("};")
    return lines


def main() -> None:
    imem_origin, imem = contiguous_image(
        parse_verilog_words(BUILD_DIR / "imem.hex"), IMEM_WORDS, "IMEM"
    )
    dmem_origin, dmem = contiguous_image(
        parse_verilog_words(BUILD_DIR / "dmem.hex"), DMEM_WORDS, "DMEM"
    )
    activation0 = parse_plain_hex(GENERATED_DIR / "activation0.hex")
    weight = parse_plain_hex(GENERATED_DIR / "weight_128.hex")

    if imem_origin != 0:
        raise ValueError(f"IMEM must start at word 0, got {imem_origin:#x}")
    if len(activation0) != ACT_WORDS or any(activation0[INPUT_WORDS:]):
        raise ValueError("Activation 0 must contain only the 25-word input followed by zero padding")
    if len(weight) != WEIGHT_WORDS:
        raise ValueError("Weight image is not exactly 400 KiB")
    if any(weight[WEIGHT_USED_WORDS:]):
        raise ValueError("Weight padding after the used 378112 bytes is not zero")

    lines = [
        "/* Generated by generate_wide_bdot_vitis_images.py; do not edit. */",
        "#ifndef WIDE_BDOT_IMAGES_H",
        "#define WIDE_BDOT_IMAGES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define WIDE_BDOT_IMEM_IMAGE_ORIGIN_WORD {imem_origin}U",
        f"#define WIDE_BDOT_IMEM_IMAGE_WORDS {len(imem)}U",
        f"#define WIDE_BDOT_DMEM_IMAGE_ORIGIN_WORD {dmem_origin}U",
        f"#define WIDE_BDOT_DMEM_IMAGE_WORDS {len(dmem)}U",
        f"#define WIDE_BDOT_ACTIVATION_INPUT_WORDS {INPUT_WORDS}U",
        f"#define WIDE_BDOT_WEIGHT_IMAGE_WORDS {WEIGHT_USED_WORDS}U",
        "",
    ]
    lines.extend(render_array("wide_bdot_imem_image", imem))
    lines.append("")
    lines.extend(render_array("wide_bdot_dmem_image", dmem))
    lines.append("")
    lines.extend(render_array("wide_bdot_activation_input", activation0[:INPUT_WORDS]))
    lines.append("")
    lines.extend(render_array("wide_bdot_weight_image", weight[:WEIGHT_USED_WORDS]))
    lines.extend(["", "#endif /* WIDE_BDOT_IMAGES_H */", ""])
    OUTPUT.write_text("\n".join(lines), encoding="ascii")

    print(f"IMEM:  origin={imem_origin:#x}, words={len(imem)}")
    print(f"DMEM:  origin={dmem_origin:#x}, words={len(dmem)}")
    print(f"ACT0:  input words={INPUT_WORDS}, allocated words={ACT_WORDS}")
    print(f"WEIGHT: used words={WEIGHT_USED_WORDS}, allocated words={WEIGHT_WORDS}")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
