#!/usr/bin/env python3
"""Generate the self-contained eBNN BDOT128 image header for the A53 loader."""

import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
EBNN_DIR = PROJECT_DIR / "software" / "ebnn"
BUILD_DIR = EBNN_DIR / "build" / "bdot128"
GENERATED_DIR = EBNN_DIR / "generated"
OUTPUT = SCRIPT_DIR / "ebnn_bdot_images.h"

IMEM_WORDS = 128 * 1024 // 4
DMEM_WORDS = 64 * 1024 // 4
WEIGHT_WORDS = 400 * 1024 // 4


def parse_verilog_words(path: Path) -> dict[int, int]:
    address = 0
    memory: dict[int, int] = {}
    for token in path.read_text(encoding="ascii").split():
        if token.startswith("@"): 
            address = int(token[1:], 16)
        else:
            if address in memory:
                raise ValueError(f"duplicate word address {address:#x} in {path}")
            memory[address] = int(token, 16)
            address += 1
    if not memory:
        raise ValueError(f"empty image: {path}")
    return memory


def contiguous_image(memory: dict[int, int], capacity: int, name: str):
    first = min(memory)
    last = max(memory)
    if last >= capacity:
        raise ValueError(f"{name} last word {last:#x} exceeds capacity {capacity:#x}")
    return first, [memory.get(index, 0) for index in range(first, last + 1)]


def render_array(symbol: str, values: list[int]) -> list[str]:
    lines = [f"static const uint32_t {symbol}[{len(values)}U] = {{"]
    for index in range(0, len(values), 4):
        chunk = values[index:index + 4]
        lines.append("    " + ", ".join(f"0x{word:08X}U" for word in chunk) + ",")
    lines.append("};")
    return lines


def main() -> None:
    imem_origin, imem = contiguous_image(
        parse_verilog_words(BUILD_DIR / "imem.hex"), IMEM_WORDS, "IMEM"
    )
    dmem_origin, dmem = contiguous_image(
        parse_verilog_words(BUILD_DIR / "dmem.hex"), DMEM_WORDS, "DMEM"
    )
    weight = [
        int(line, 16)
        for line in (GENERATED_DIR / "weight_128.hex").read_text(encoding="ascii").splitlines()
    ]
    metadata = json.loads(
        (GENERATED_DIR / "ebnn_bdot_metadata.json").read_text(encoding="utf-8")
    )
    weight_used_words = (int(metadata["weight_bytes_used"]) + 3) // 4

    if imem_origin != 0:
        raise ValueError(f"IMEM must start at word 0, got {imem_origin:#x}")
    if len(weight) != WEIGHT_WORDS:
        raise ValueError("Weight image is not exactly 400 KiB")
    if weight_used_words > WEIGHT_WORDS or any(weight[weight_used_words:]):
        raise ValueError("Invalid eBNN Weight BRAM used range or padding")

    lines = [
        "/* Generated by generate_ebnn_bdot_vitis_images.py; do not edit. */",
        "#ifndef EBNN_BDOT_IMAGES_H",
        "#define EBNN_BDOT_IMAGES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define EBNN_BDOT_IMEM_IMAGE_ORIGIN_WORD {imem_origin}U",
        f"#define EBNN_BDOT_IMEM_IMAGE_WORDS {len(imem)}U",
        f"#define EBNN_BDOT_DMEM_IMAGE_ORIGIN_WORD {dmem_origin}U",
        f"#define EBNN_BDOT_DMEM_IMAGE_WORDS {len(dmem)}U",
        f"#define EBNN_BDOT_WEIGHT_IMAGE_WORDS {weight_used_words}U",
        "",
    ]
    lines.extend(render_array("ebnn_bdot_imem_image", imem))
    lines.append("")
    lines.extend(render_array("ebnn_bdot_dmem_image", dmem))
    lines.append("")
    lines.extend(render_array("ebnn_bdot_weight_image", weight[:weight_used_words]))
    lines.extend(["", "#endif /* EBNN_BDOT_IMAGES_H */", ""])
    OUTPUT.write_text("\n".join(lines), encoding="ascii")

    print(f"IMEM: origin={imem_origin:#x}, words={len(imem)}")
    print(f"DMEM: origin={dmem_origin:#x}, words={len(dmem)}")
    print(f"ACT0/ACT1: cleared by loader")
    print(f"WEIGHT: used words={weight_used_words}, allocated words={WEIGHT_WORDS}")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
