#!/usr/bin/env python3
"""Generate the self-contained FINN LFC images used by the A53 loader."""

from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
BUILD_DIR = PROJECT_DIR / "software" / "build"
OUTPUT = SCRIPT_DIR / "pipeline_lfc_images.h"

IMEM_WORDS = 128 * 1024 // 4
DMEM_WORDS = 512 * 1024 // 4


def parse_verilog_words(path: Path) -> dict[int, int]:
    address = 0
    memory: dict[int, int] = {}
    for token in path.read_text(encoding="ascii").split():
        if token.startswith("@"):
            address = int(token[1:], 16)
        else:
            if address in memory:
                raise ValueError(f"duplicate word address {address:#x} in {path}")
            memory[address] = int(token, 16)
            address += 1
    if not memory:
        raise ValueError(f"empty image: {path}")
    return memory


def contiguous_image(
    memory: dict[int, int], capacity: int, name: str
) -> tuple[int, list[int]]:
    first = min(memory)
    last = max(memory)
    if last >= capacity:
        raise ValueError(f"{name} last word {last:#x} exceeds capacity {capacity:#x}")
    return first, [memory.get(index, 0) for index in range(first, last + 1)]


def render_array(symbol: str, values: list[int]) -> list[str]:
    lines = [f"static const uint32_t {symbol}[{len(values)}U] = {{"]
    for index in range(0, len(values), 4):
        chunk = values[index:index + 4]
        lines.append("    " + ", ".join(f"0x{word:08X}U" for word in chunk) + ",")
    lines.append("};")
    return lines


def main() -> None:
    imem_origin, imem = contiguous_image(
        parse_verilog_words(BUILD_DIR / "imem.hex"), IMEM_WORDS, "IMEM"
    )
    dmem_origin, dmem = contiguous_image(
        parse_verilog_words(BUILD_DIR / "dmem.hex"), DMEM_WORDS, "DMEM"
    )
    if imem_origin != 0:
        raise ValueError(f"IMEM must start at word 0, got {imem_origin:#x}")

    lines = [
        "/* Generated by generate_pipeline_lfc_vitis_images.py; do not edit. */",
        "#ifndef PIPELINE_LFC_IMAGES_H",
        "#define PIPELINE_LFC_IMAGES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define PIPELINE_LFC_IMEM_ORIGIN_WORD {imem_origin}U",
        f"#define PIPELINE_LFC_IMEM_WORDS {len(imem)}U",
        f"#define PIPELINE_LFC_DMEM_ORIGIN_WORD {dmem_origin}U",
        f"#define PIPELINE_LFC_DMEM_WORDS {len(dmem)}U",
        "",
    ]
    lines.extend(render_array("pipeline_lfc_imem", imem))
    lines.append("")
    lines.extend(render_array("pipeline_lfc_dmem", dmem))
    lines.extend(["", "#endif /* PIPELINE_LFC_IMAGES_H */", ""])
    OUTPUT.write_text("\n".join(lines), encoding="ascii")

    print(f"IMEM: origin={imem_origin:#x}, words={len(imem)}")
    print(f"DMEM: origin={dmem_origin:#x}, words={len(dmem)}")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
