`timescale 1ns/1ps

// FPGA wrappers for the byte-address contract used by wide_bram_32xwide_model.
// The instantiated IPs are generated by scripts/create_wide_bram_ips.tcl.
module wide_activation_bram_bmg_wrapper (
    input  wire          cpu_clk,
    input  wire          cpu_en,
    input  wire [3:0]    cpu_we,
    input  wire [31:0]   cpu_addr_byte,
    input  wire [31:0]   cpu_wdata,
    output wire [31:0]   cpu_rdata,
    input  wire          accel_clk,
    input  wire          accel_en,
    input  wire [31:0]   accel_addr_byte,
    output wire [127:0]  accel_rdata,
    output wire          cpu_addr_misaligned,
    output wire          accel_addr_misaligned
);
    assign cpu_addr_misaligned = |cpu_addr_byte[1:0];
    assign accel_addr_misaligned = |accel_addr_byte[3:0];

    activation_bram_32x128 memory (
        .clka(cpu_clk),
        .ena(cpu_en),
        .wea(cpu_we),
        .addra(cpu_addr_byte[14:2]),
        .dina(cpu_wdata),
        .douta(cpu_rdata),
        .clkb(accel_clk),
        .enb(accel_en),
        .web(16'b0),
        .addrb(accel_addr_byte[14:4]),
        .dinb(128'b0),
        .doutb(accel_rdata)
    );
endmodule

module wide_weight_bram_bmg_wrapper (
    input  wire          load_clk,
    input  wire          load_en,
    input  wire [3:0]    load_we,
    input  wire [31:0]   load_addr_byte,
    input  wire [31:0]   load_wdata,
    output wire [31:0]   load_rdata,
    input  wire          accel_clk,
    input  wire          accel_en,
    input  wire [31:0]   accel_addr_byte,
    output wire [127:0]  accel_rdata,
    output wire          load_addr_misaligned,
    output wire          accel_addr_misaligned
);
    assign load_addr_misaligned = |load_addr_byte[1:0];
    assign accel_addr_misaligned = |accel_addr_byte[3:0];

    weight_bram_400k_32x128 memory (
        .clka(load_clk),
        .ena(load_en),
        .wea(load_we),
        .addra(load_addr_byte[18:2]),
        .dina(load_wdata),
        .douta(load_rdata),
        .clkb(accel_clk),
        .enb(accel_en),
        .web(16'b0),
        .addrb(accel_addr_byte[18:4]),
        .dinb(128'b0),
        .doutb(accel_rdata)
    );
endmodule
