# ==============================================================================
# CPU 30 MHz / BRAM 90 MHz timing constraints
# ==============================================================================
# Current clocking in src/bd/design_1_edit.tcl:
#   clk_cpu  : 30 MHz, period 33.333 ns
#   clk_bram : 90 MHz, period 11.111 ns, phase 0 deg
#
# Both clocks are generated by the same clk_wiz/MMCM, so Vivado should keep them
# related and analyze paths between them. Do not add set_clock_groups -asynchronous
# or broad set_false_path constraints between clk_cpu and clk_bram.
#
# Important functional intent:
#   CPU edge -> first valid BRAM edge:
#     PC, data_addr, write_data, and we must be stable by the next 90 MHz BRAM
#     rising edge, about 11.111 ns after the CPU edge.
#
#   IMEM BRAM dout -> decode/regfile/ALU -> DMEM addr:
#     This same-instruction path must settle within the BRAM-cycle timing that
#     feeds the following DMEM access. Do not relax all BRAM-launched paths.
#
#   DMEM BRAM dout -> load align/sign extend -> regfile writeback:
#     Load data must be stable before the next CPU rising edge.
#
# Therefore no global multicycle exception is applied here. A broad exception such
# as CPU->BRAM setup 3 or BRAM->CPU setup -start 3 would allow paths to take a full
# CPU cycle and would hide violations of the intended first-BRAM-edge behavior.
#
# If a future implementation proves that a specific, named path is functionally
# allowed to use more than one BRAM cycle, constrain only that narrow path with
# explicit -from/-to pins or cells after reviewing report_timing.
# ==============================================================================

